### PR TITLE
Add config option to exclude sites and change total power to W instead of kW

### PR DESCRIPTION
**Pull request by olalid**
This pull request has several parts:
1. Add a config option to be able to disable a site to create less unnecessary sensors. I have 2 sites with a charger at each, and a HA at each location, so makes no sense to have all sensors at both locations for me.
2. Change the total_power sensor to W instead of kW. Just makes more sense to me at least. Todo is to figure out how to get rid of the decimal point.
3. FIx a sort of a bug: add a check that a sensor actually exists before trying to create it. I.e. "if key in SENSOR_TYPES:". I noticed when upgrading to a new version that it tried to create a sensor that did not exist anymore and crashed during init.

### CODE REVIEW

**Comment by fondberg** [comment]
@olalid can you remove the total power change so we can do that in another PR and get this merged?

**Comment by olalid** [comment]
> @olalid can you remove the total power change so we can do that in another PR and get this merged?

Yes, done I think...

**Comment by fondberg** [comment]
You wanna try a release yourself? Just merge this and checkout master of this repo and do a make bump then check it in and go to releases and create a release out from master.

**Comment by olalid** [comment]
> You wanna try a release yourself? Just merge this and checkout master of this repo and do a make bump then check it in and go to releases and create a release out from master.

Ok, I think that was it. :)

**Pull request merged**
