### PR TITLE
Update on servicecalls

### PR DESCRIPTION
**Pull request by Hellowlol**

### CODE REVIEW

**Comment by fondberg** [comment]
I think we should move ahead with this and try if it works

**Review by fondberg — APPROVED** [review]

**Comment by Hellowlol** [comment]
Should we add some delay to the calls?

**Comment by fondberg** [comment]
That is probably a good idea.

**Comment by olalid** [comment]
This may have become redundant after SignalR protocol has been implemented?

**Comment by Hellowlol** [comment]
I havnt done anything after Easee issues lately.

**Pull request closed without merging**
