### PR TITLE
Change const.py to reflect new defintitions in HA Core

### LINKED ISSUE #125: Integration fails to start on latest HA core-2021.8.0b4
The Easee integration fails to start on the latest beta. It fails with the following message:

> Logger: homeassistant.setup

>Source: setup.py:173 
>First occurred: 9:48:42 (1 occurrences) 
>Last logged: 9:48:42

>Setup failed for easee: Unable to import component: cannot import name >'ELECTRICAL_CURRENT_AMPERE' from 'homeassistant.const' >(/usr/src/homeassistant/homeassistant/const.py)

Please let me know if you need more logs or similar.

### PR DESCRIPTION
**Pull request by henrikeri**
Changed constants to reflect new definitions in HA Core. Test on my own setup, working as before.

Closes #125

### CODE REVIEW

**Comment by tmjo** [comment]
Think we should add some backwards compatibility to this, otherwise the integration will no longer load for people who didn't yet update. What do you think about a try/except with new/old imports?

**Comment by tmjo** [comment]
Proposed a change, please see if ok. I tested on both new and "old" version of HA.

**Comment by henrikeri** [comment]
> Proposed a change, please see if ok. I tested on both new and "old" version of HA.
Look good. Tested successfully on 2021.7 and 2021.8 here as well.

**Review by astrandb — APPROVED** [review]
Looks good!

**Comment by olalid** [comment]
Looks good!

**Pull request merged**
