### PR TITLE
Clean removal of entities

### PR DESCRIPTION
**Pull request by astrandb**
Improved handling of the unselecting of entities and the following cleanup.

I cannot verify that it works for eq-sensors since I don't have access to an Equalizer.

### CODE REVIEW

**Comment by olalid** [comment]
For me, the binary_sensors did not get created directly after the update, I had to change the settings to remove one binary_sensor and add it again. Or that was what I did at least to make it work again.

I also get an error when the equalizer status sensor is updated:
2020-10-23 08:27:53 DEBUG (MainThread) [custom_components.easee.sensor] EqualizerEntity async_update : QH000273 status
2020-10-23 08:27:53 INFO (MainThread) [homeassistant.components.automation.elbil_trigger] Elbil Trigger: Running automation actions
2020-10-23 08:27:53 INFO (MainThread) [homeassistant.components.automation.elbil_trigger] Elbil Trigger: Executing step call service
2020-10-23 08:27:53 INFO (MainThread) [homeassistant.components.automation.elbil_trigger] Elbil Trigger: Executing step delay 0:00:01
2020-10-23 08:27:53 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/var/opt/homeassistant/custom_components/easee/controller.py", line 264, in refresh_sites_state
    self.update_ha_state()
  File "/var/opt/homeassistant/custom_components/easee/controller.py", line 182, in update_ha_state
    entity.async_schedule_update_ha_state(True)
  File "/var/opt/homeassistant/havenv/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 438, in async_schedule_update_ha_state
    assert self.hass is not None
AssertionError

Sorry I do not have time right now to dig deeper.

**Comment by astrandb** [comment]
@olalid I can't reproduce the issue with binary_sensor. Greatful if you can pinpoint when it happens. Unfortunately it is difficult do debug equalizer related problem when you haven't got one.

**Comment by olalid** [comment]
Yes, I understand that it is difficult to understand with the limited info I provided.

**Review by olalid — APPROVED** [review]
Great job @astrandb

**Comment by olalid** [comment]
> @olalid I can't reproduce the issue with binary_sensor. Greatful if you can pinpoint when it happens. Unfortunately it is difficult do debug equalizer related problem when you haven't got one.

Problem solved.

**Comment by olalid** [comment]
Hold on, I just discovered that the removal of equalizer sensors does not work for some reason. Investigating...

**Comment by olalid** [comment]
I fixed the equalizer removal bugs and merged to this branch.

**Review by astrandb — COMMENTED** [review]
Looks good

**Comment by astrandb** [comment]
@olalid I don't know what happened when you added your fix. Suddenly this PR contains some 15 commits from you that seem to be old and irrelevant here. The resulting code is OK but I suggest that you check so you base your changes on correct branch.

@fondberg @tmjo I think this PR is as good as it gets for now. I should be squashed & merged.

**Comment by olalid** [comment]
> @olalid I don't know what happened when you added your fix. Suddenly this PR contains some 15 commits from you that seem to be old and irrelevant here. The resulting code is OK but I suggest that you check so you base your changes on correct branch.
> 
> @fondberg @tmjo I think this PR is as good as it gets for now. I should be squashed & merged.

Yeah, I am not a git guru, so I messed up a bit I guess.

**Pull request merged**
