### PR TITLE
Use controller and move to use site state

### PR DESCRIPTION
**Pull request by fondberg**
This PR moves all biz logic into a controller and uses site state for charger config and charger state. It also uses different timers for refreshing data (60s for state + config) 10mins for schedules and 15mins for charging consumption

### CODE REVIEW

**Review by olalid — APPROVED** [review]

**Comment by fondberg** [comment]
I pushes an optimization to use the new site state. I will release that library version now and perhaps we can retest. I think it is much cleaner now and way more optimized

**Comment by olalid** [comment]
About schedule polling, i.e. SCAN_INTERVAL_SCHEDULES_SECONDS. I wonder if it is ok to poll *one* schedule every minute?
I.e. if you have 3 schedules that are polled, could a round-robin approach work? I.e. poll schedule 1, wait one minute, poll schedule 2, wait one minute, poll schedule 3, and so on?

**Comment by fondberg** [comment]
Is that necessary? I mean it sounds a bit complicated because right now one can have 1 schedule per charger and it doesn't update that much. I wonder if anyone will create an automation with these values changing?

**Comment by olalid** [comment]
No, not necessary, just a thought. :)

**Comment by fondberg** [comment]
It is a good idea. Just don't know how to implement it in an easy way

**Pull request merged**
