### PR TITLE
Equalizer changes

### PR DESCRIPTION
**Pull request by olalid**
Separate equalizer sensor config from charger sensor config.
Add support for attribute rounding on equalizer sensors.
Remove decimals from Max/Dynamic current sensors.

### CODE REVIEW

**Comment by olalid** [comment]
@tmjo there are a few new translations needed.

**Review by fondberg — APPROVED** [review]

**Comment by astrandb** [comment]
OK with me.

I found a little spelling error - "Equalzier" - on two places in controller.py. It is not found during execution in my setup but the linter found it.

**Comment by tmjo** [comment]
Looks ok to me too. Committed updated nb translation. I also saw the spelling error that astrandb mentioned.

**Review by astrandb — APPROVED** [review]
Looks good!

**Comment by olalid** [comment]
> OK with me.
> 
> I found a little spelling error - "Equalzier" - on two places in controller.py. It is not found during execution in my setup but the linter found it.

Fixed.

**Review by tmjo — APPROVED** [review]

**Pull request merged**
